services:
  postgres:
    image: bitnami/postgresql:latest
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DB}
    ports:
      - 5432:5432
    volumes:
      - pizzashop_pg_data:/bitnami/postgresql

volumes:
  pizzashop_pg_data:
